server {
    listen 9090;

    location / {
        proxy_pass http://backtrack-agent:9090;

        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods "GET, POST, OPTIONS";
        add_header Access-Control-Allow-Headers "*";

        if ($request_method = OPTIONS) {
            return 204;
        }
    }
}
